# 头部菜单，title: link
menu:
  首页: /
  标签: /tags
  归档: /archives
  收藏: /collect
  todo: /todo
  关于: /about

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: true

# 默认音乐（随机播放）
mp3:
  - https://common-1258538316.cos.ap-guangzhou.myqcloud.com/bgm-zelda.mp3

# 首页封面图, 为空时取文章的cover作为封面(注意跨域问题,建议使用同源图片)
welcome_cover:
  - /assets/img/snapsee/DSC02975-01.jpeg
  - /assets/img/snapsee/DSC03005-01.jpeg
  - /assets/img/snapsee/20160618_164809-01.jpeg
  - /assets/img/snapsee/20160618_181335-01-01.jpeg
  - /assets/img/snapsee/DSC03075-01.jpeg
  - /assets/img/snapsee/DSC03078-01.jpeg
  - /assets/img/snapsee/DSC02984-01.jpeg
  - /assets/img/snapsee/20160628_193430-01-01.jpeg

# 默认文章封面图（随机调用,支持外链）
cover:
  - /assets/img/snapsee/2016-03-26 205142-01.jpeg
  - /assets/img/snapsee/20160508_142121-01.jpeg
  - /assets/img/snapsee/20160515_230654-01.jpeg
  - /assets/img/snapsee/DSC00632-01.jpeg
  - /assets/img/snapsee/DSC00674-01.jpeg
  - /assets/img/snapsee/DSC01052-01.jpeg
  - /assets/img/snapsee/DSC01155-01.jpeg
  - /assets/img/snapsee/DSC01170-02.jpeg
  - /assets/img/snapsee/DSC03075-01.jpeg
  - /assets/img/snapsee/DSC03078-01.jpeg
  - /assets/img/snapsee/DSC02984-01.jpeg
  - /assets/img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg
  # - /assets//img/snapsee/20160628_193430-01-01.jpeg

# 是否使用mathjax
mathjax: false

# 是否关闭默认滚动条
scrollbar: true

# 本地搜索,请将索引文件放在网站根目录,或修改主题js文件的path值
local_search:
  # 是否启用
  enable: true

# 是否显示 一言(hitokoto)
hitokoto: true

# 链接(可选:facebook,twitter,github,wechat,email)
links:
  # facebook: /
  # twitter: /
  github: https://github.com/HelloWorld20
  wechat: /img/logo.png
  email: mailto:292701515@qq.com

# 备案
beian:
  # 是否显示备案信息
  enable: true
  # 是否在主页面最底下显示备案信息(虽然丑，但是完全满足规定要求)
  enableFooter: true
  # 备案号
  beianInfo: 粤ICP备20038895号
  # 链接地址
  link: http://beian.miit.gov.cn/

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否启用评论功能
  enable: false
  # 是否自动展开评论框
  autoExpand: false
  # 应用编号
  clientID: ""
  # 应用秘钥
  clientSecret: ""
  # issue仓库名
  repo: ""
  # Github名
  owner: ""
  # Github名
  admin: [""]
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: false

# 网站关键字
keywords: Fechin

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics: UA-175169156-1

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
